In [2]:
import numpy as np
import os

<h2 style="color: green;">NumPy</h2>

 NumPy는 파이썬의 기본 자료구조보다 더 큰 규모의 다차원 배열 및 행렬 연산을 지원하는 라이브러리로서, 다양한 분야에서 널리 사용되고 있습니다.

 인공지능에서도 NumPy의 다차원 배열 및 행렬 연산 기능이 많이 활용됩니다. 예를 들어, 딥러 닝에서는 수많은 가중치와 편향 값들을 NumPy 배열로 관리하며, 각 층 사이의 연산 역시 Num Py의 행렬 연산을 기반으로 수행됩니다.

 따라서 NumPy는 인공지능 분야에서 필수적인 라이브러리 중 하나입니다. 이를 통해 효율적인 계산과 연산 속도를 얻을 수 있습니다.


### *단일 객체 저장 및 불러오기*

In [3]:
#단일 객체 생성
array = np.arange(1, 10)
print(array)

[1 2 3 4 5 6 7 8 9]


In [4]:
#numpy 형태로 저장
os.makedirs("./data", exist_ok=True)
np.save("./data/save.npy", array)

In [5]:
#numpy 데이터 불러오기
result = np.load("./data/save.npy")
print(result)

[1 2 3 4 5 6 7 8 9]


### *복수 객체 저장 및 불러오기*

In [6]:
#복수 객체 생성
array01 = np.arange(0,10)
array02 = np.arange(10,20)
array03 = np.arange(20,30)

In [7]:
#numpy 저장
np.savez('./data/mul_save.npz', array1=array01, array2=array02, array3=array03)

In [8]:
#numpy 불러오기
data = np.load('./data/mul_save.npz')

result01 = data['array1']
result02 = data['array2']
result03 = data['array3']

print(array01)
print(array02)
print(array03)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24 25 26 27 28 29]


### *정렬(기본 오름차순)*

In [50]:
array = np.array([5, 20, 30, 2, 4, 8])
array.sort()
print(array)

[ 2  4  5  8 20 30]


### 정렬(내림 차순)

In [51]:
print(array[::-1])

[30 20  8  5  4  2]


### *원소의 정렬 - 각 열, 행을 기준으로 정렬*

In [52]:
array1 = np.array([[5, 2, 3, 4, 20], [7, 9, 10, 4, 45]])
print(array1)
org_array = array1.copy()

[[ 5  2  3  4 20]
 [ 7  9 10  4 45]]


In [53]:
#정렬 전
print(array1)

[[ 5  2  3  4 20]
 [ 7  9 10  4 45]]


In [54]:
#각 열을 기준으로 정렬 후
array1.sort(axis=0)
print(array1)

[[ 5  2  3  4 20]
 [ 7  9 10  4 45]]


In [55]:
#각 행을 기준으로 정렬
array1.sort(axis=1)
print(array1)

[[ 2  3  4  5 20]
 [ 4  7  9 10 45]]


### *균일한 간격으로 데이터 생성*

In [56]:
array2 = np.linspace(0,4,3)
print(array2)

[0. 2. 4.]


### *난수의 재연*

In [57]:
np.random.seed(444)
print(np.random.randint(0, 10, (2,3)))

[[3 0 7]
 [8 3 4]]


### *배열 객체 복사*

In [58]:
array1 = np.arange(0,10)
array2 = array1

array2[0] = 99
print(array1, array2)

[99  1  2  3  4  5  6  7  8  9] [99  1  2  3  4  5  6  7  8  9]


In [59]:
array3 = np.arange(0,10)
array4 = array3.copy()

array4[0] = 99
print(array3, array4)

[0 1 2 3 4 5 6 7 8 9] [99  1  2  3  4  5  6  7  8  9]


### *중복된 원소 제거*

In [60]:
array5 = np.array([2,2,2,2,2,3,3,1,1,4])
print("원본 >>", array5)
temp = np.unique(array5)
print("중복 제거 >>", temp)

원본 >> [2 2 2 2 2 3 3 1 1 4]
중복 제거 >> [1 2 3 4]


### *브로드 캐스팅*

In [9]:
A = np.array([[1,2,3], [4,5,6]])
B = np.array([10,20,30])

#브로드캐스팅을 통한 요소별 덧셈 연산
C = A + B
print(C)

[[11 22 33]
 [14 25 36]]
