<h1 style="color: blue;">1. 다양한 데이터 처리 방법</h1>

데이터를 생성해서 무사히 저장하기까지 일련의 과정을 데이터 파이프라인이라고 합니다.

1. 데이터 생성
2. 데이터 수집
3. 데이터 가공 후 저장(ETL : 데이터 추출, 변환, 적재를 묶어서 ETL이라고 부릅니다. )
4. 데이터 시각화(BI)

<h2 style="color: green;">데이터프레임과 데이터레이크</h2>

+ 데이터 웨어하우스(data warehouse) : 사용자의 의사 결정에 도움을 주기 위하여 기간시스템의 데이터 베이스에 축적된 데이터를 공통의 형식으로 변환해서 관리하는 데이터베이스를 말합니다. 줄여서 DW로도 불립니다.

    즉 데이터 웨어하우스는 방대한 조직 내에서 분산 운영되는 각각의 데이터 베이스 관리 시스템들을 효 율적으로 통합하여 조정 관리 하는 것을 의미합니다.
<br></br>
+ 데이터 레이크 : 구조화되거나 반구조화되거나 구조화되지 않은 대량의 데이터를 저장, 처리, 보호하기 위한 중앙 집중식 저장소입니다.

<h2 style="color: green;">데이터분석 프로세스</h2>

#### 문제 정의 -> 데이터 수집 -> 데이터 전처리 -> 모델링 -> 해석 및 시각화

#### 1. 문제 정의

데이터 분석 프로세스에서 가장 중요한 단계이자 어려운 단계 문제가 제대로 설정되지 않는다면 다시 처음부터 진행하므로 시간적 손실 발생

- 분석의대상,분석목적설정
- 정의된 문제를 해결하기 위한 구체적인 계획이 수립
- 문제를 정의할 분야에 대한 비즈니스 지식이 필요
- 모든 사람들이 명료하게 이해할 수 있도록 구체적

#### 2. 데이터 수집

분석에필요한데이터를찾고모으는단계데이터의양이많다고좋은것은아니다.

- 데이터수집단계가어려운이유는데이터가존재하지않는경우혹은너무많은경우
- 비용과법적인문제가발생할수있으니주의필요
- 최근 데이터 수집 방법에는 데이터 구매, 실험환경에서 수집(스스로 데이터 생성), 웹 크롤링, open dataset을 활용하여 수집한다.

#### 3. 데이터 전처리

수집한 데이터를 바로 분석에 적용하는 경우는 거의 없다. 전처리가 필요하다. 왜냐하면 데이터를 생
생할 때 분석을 전제로 데이터를 생성하지 않았기 때문이다.

<데이터 전처리>

- 분석에 부적한 구조, 누락된 항목, NA(결측값) 존재 등으로 인해 전처리 과정이 필요하다.
- 노이즈 제거, 중복값 제거, 결측값 보정, 데이터 연계/통합, 데이터 구조 변경
- 데이터 백터화

#### 4. 모델링

원하는 결과를 도출하기 위해서 예측이든 분류, 희귀를 위한 작업을 진행하는 단계이다. 즉 전처리된
데이터를 활용하여 학습을 진행하는 단계

#### 5. 해석 및 시각화

모델링을 통해 결과를 도출되면 이를 처음 정의했던 문제와 연관시켜 문제를 해결하는 방법을 모색
하는 단계. 시각화를 통해 도출된 결과를 알아보기 쉽게 표현하고, 이를 근거로 활용

<h2 style="color: green;">정형, 비정형, 반정형</h2>

정형 데이터 : 데이터베이스의 사전에 정의된 규칙에 맞게 들어간 데이터 중에 수치 만으로 의미 파악이 쉬운 데이터를 의미합니다.

비정형 데이터 : 비정형 데이터는 정형 데이터와 반대되는 단어이다. 비정형 데이터는 형태가 없고, 연산이 불가능한 데이터를 의미한다. 정해진 규칙이 없기 때문에 데이터의 의미를 쉽게 파악하기 힘들다.

반정형 데이터 (Semi-structed data) :반정형 데이터의 반은 Semi를 의미합니다. 즉 완전한 정형이 아닌 약한 정형 데이터이다. 데이터베이스는 아니지만 스키마를 가지고 있는 형태이고, 연산이 불가능한 데이터

<h2 style="color: green;">데이터 축소</h2>

적은 양으로도 전체 데이터 집합을 잘 대표하는 데이터 얻는 과정이다. 대규모 데이터의 작업 시 분석에 필요한 줄이고 효율성을 향상시키기 위해 필요하다.

### 특성 추출을 사용한 차원 축소

+ 차원 축소를 위한 특성 추출의 목적은 특성에 내재된 정보는 많이 유지하면서 특성 집합 Poriginal 을 새로운 집합 Pnew 으로 변환하는 것입니다.
+ 고품질예측을만들기위한데이터의능력을조금만희생하고특성의수를줄입니다.
+ 특성추출기법의단점은새로운특성을사람이이해하지못한다는것입니다.
+ 모델을훈련하기위해필요한특성을담고있지만사람의눈에는무작위한숫자의모음으로보일것입니다.

### 주성분을 사용해 특성 줄이기

+ PCA는데이터의분산을유지하면서특성의수를줄이는선형차원축소기법입니다
+ PCA는타킷벡터의정보를사용하지않고특성행렬만이용하는비지도학습기법입니다
+ 데이터는 두개의 특성 x1과 x2를 가집니다
+ 그래프의 샘플들은 길이가 길고 높이는 낮은 타원 모양으로 퍼져 있는 '길이' 방향의 분산이 '높이'방향보다 훨씬 큽니다.
+ 길이와높이대신가장분산이많은방향을첫번째주성분으로부르고두번째로가장많은방향을두번째주 성분이라고 부릅니다.
+ 특성을줄이는한가지방법은2D공간의모든샘플을1차원주성분에투영하는것입니다.

### *사이킷런 손글씨 데이터를 활용하여 특성 행렬을 표준화 처리*

In [6]:
from sklearn.preprocessing import StandardScaler
from sklearn import datasets

In [7]:
digits = datasets.load_digits()  #8x8 크기의 손글씨 숫자 데이터 로드
feature = StandardScaler().fit_transform(digits.data)  #특성 행렬을 표준화 처리

print(feature)

[[ 0.         -0.33501649 -0.04308102 ... -1.14664746 -0.5056698
  -0.19600752]
 [ 0.         -0.33501649 -1.09493684 ...  0.54856067 -0.5056698
  -0.19600752]
 [ 0.         -0.33501649 -1.09493684 ...  1.56568555  1.6951369
  -0.19600752]
 ...
 [ 0.         -0.33501649 -0.88456568 ... -0.12952258 -0.5056698
  -0.19600752]
 [ 0.         -0.33501649 -0.67419451 ...  0.8876023  -0.5056698
  -0.19600752]
 [ 0.         -0.33501649  1.00877481 ...  0.8876023  -0.26113572
  -0.19600752]]


1. StandardScaler() 
>> Scikit-learn의 전처리(preprocessing) 모듈에서 제공되는 클래스 중 하나입니다. 이 클래스는 데이터를 평균이 0, 분산이 1인 가우시안 정규 분포(standard normal distribution)로 변환합니다.

 

2. digits.data : digits 데이터셋에서 숫자 이미지의 각 픽셀 값을 포함하는 배열
<br></br>
3. fit_transform() 메서드
>> StandardScaler 클래스에는 데이터를 변환하는 두 가지 단계가 있습니다. 첫째, 모델을 학습(fit)하고, 둘째, 학습된 모델을 사용하여 데이터를 변환(transform)합니다. fit_transform() 메서드는 이 두 단계를 한 번에 수행합니다. 즉, 데이터를 표준화(normalize)하고, 변환된 값을 반환합니다.

따라서 위의 코드는 digits 데이터셋의 특성을 가우시안 정규 분포로 변환한 후, 변환된 값을 featuress 변수에 할당 이렇게 정규화를 수행하면, 모델이 데이터를 더 잘 이해하고, 모델의 예측 성능을 향상 시킬 수 있습니다.

### *99%의 분산을 유지하도록 PCA 클래스 객체 생성*

In [10]:
from sklearn.decomposition import PCA

In [11]:
pca = PCA(n_components = 0.99, whiten=True)
features_pca = pca.fit_transform(feature)  #PCA 수행

print("원본 특성 개수 >> ", feature.shape[1])
print("줄어든 특성 개수 >> ", features_pca.shape[1])

원본 특성 개수 >>  64
줄어든 특성 개수 >>  54


PCA 클래스: Scikit-learn의 decomposition 모듈에서 제공되는 클래스 중 하나입니다. PCA는 데이터셋의 차원을 감소시키는 기술로, 데이터셋에서 가장 중요한 특성만 추출하여 새로운 차원 축으로 변환합니다. 이를 통해 데이터셋의 노이즈(noise)를 제거하고, 더욱 빠르고 효율적인 학습이 가능해집니다.

n_components: PCA 클래스의 인자 중 하나로, 추출할 주성분(principal component)의 수를 지정합니다. 여기서는 99%의 분산(variance)을 유지하도록 설정되어 있습니다. 이는 데이터셋에서 99%의 정보가 유지되도록 차원을 축소하는 것을 의미합니다.

whiten: PCA 클래스의 인자 중 하나로, True로 설정할 경우 PCA의 결과로 나오는 주성분들이 서로 독립적인 값이 되도록 백색화(whitening)를 수행합니다. 백색화를 하면 각 주성분의 분산이 1이 되고, 상관 관계가 없는 성분들로 구성된 새로운 특성 공간이 만들어집니다.

위의 같이 PCA이용하면 99%의 분산을 유지하도록 새로운 특성(feature) 공간으로 변환하고 있습니다. 결과적으로, 원본 데이터셋의 특성 개수는 features.shape[1]으로 확인할 수 있고, PCA를 수행하여 감소된 특성 개수는 features_pca.shape[1]으로 확인할 수 있습니다. 이렇게 차원 축소를 수행하면, 모델의 학습 시간을 단축시키고, 과적합(overfitting)을 방지할 수 있습니다.

### *사이킷 런 손글씨 데이터를 활용하여 주성분 줄이기 차이(결과값 비교)*

In [13]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [15]:
digits = load_digits()

#진짜 차이가 있는지 체크 하기 위해서 -> 정규화 하지 않은 데이터로 분류 모델 훈련
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target,test_size=0.1, random_state=777)

print(len(x_train), len(x_test))
print(len(y_train), len(y_test))

# 8 : 2
# 2 -> 1 : 1
# 8 : 1 : 1

# 1.폴더 생성 (이미지 100개)
# 2.폴더 읽고 -> train val test 나눠서 폴더 생성해서 거기에 이미지 저장 

1617 180
1617 180


In [16]:
#모델 불러오기
model = LogisticRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

no_standardScaler_acc_score = accuracy_score(y_test, y_pred)  #정답지 예측치
print(no_standardScaler_acc_score)

0.9444444444444444


/Users/sang-yun/anaconda3/envs/AI/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


### *StandardScaler 적용 후 -> 평가*

In [17]:
scaler = StandardScaler()
x_train_norm = scaler.fit_transform(x_train)
x_test_norm = scaler.transform(x_test)
model_norm = LogisticRegression()
model_norm.fit(x_train_norm, y_train)
y_pred_norm = model_norm.predict(x_test_norm)

standardScale_acc_score = accuracy_score(y_test, y_pred_norm)
print(standardScale_acc_score)

0.9444444444444444


### *선형적으로 구분되지 않는 데이터의 차원 축소*

In [18]:
from sklearn.decomposition import KernelPCA
from sklearn.datasets import make_circles

In [19]:
#선형적으로 구분되지 않은 데이터를 만들기
feature, _ = make_circles(n_samples=1000, random_state=777, noise=0.1, factor=0.1)
#make_circles는 feature과 label 두개의 값이 반환된다.
print(feature)

#make_circles는 원모양의 데이터셋을 생성하므로서 비선형 데이터셋이다.

[[-0.02313275  0.15282194]
 [ 0.8626983   0.46556009]
 [ 0.05905661 -0.05048386]
 ...
 [-0.10071513 -0.1814104 ]
 [ 0.10461224  0.08710802]
 [ 0.28894733  0.97460534]]


### *방사 기저 함수를 사용하여 커널 PCA를 적용*

In [24]:
kcpa = KernelPCA(kernel = 'rbf', gamma=15, n_components=1)
#kcpa rbf
feature_rbf = kcpa.fit_transform(feature)
print("원본 특성 개수 : ", feature.shape[1])
print("줄어든 특성 개수 : ", feature_rbf.shape[1])
#.shape[]은 튜플형태로 반환 [0]은 행의 개수 [1]은 열의 개수

원본 특성 개수 :  2
줄어든 특성 개수 :  1


### *선형 판별 분석 LDA 실습*

In [25]:
from sklearn import datasets
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [26]:
iris = datasets.load_iris()  #붓꽃 데이터셋 로드
features = iris.data
target = iris.target

print(features, target)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [27]:
lda = LinearDiscriminantAnalysis(n_components=1)
feature_lda = lda.fit(features, target).transform(features)

print("원본 특성 개수 >> ", features.shape[1])
print("줄어든 특성 개수 >> ", feature_lda.shape[1])

원본 특성 개수 >>  4
줄어든 특성 개수 >>  1
